global using HealthCare.Application.Contract.IServices;
global using Microsoft.Extensions.DependencyInjection;
global using HealthCare.Infrastructure.Services;
global using AutoMapper;
global using HealthCare.Infrastructure.DI.Services;
global using Common.JWT;
global using Common.JWT.Interface;
global using HealthCare.Common.Models.Dtos.Response.Doctor;
global using HealthCare.Domain.Doctor;
